#!/bin/bash

TOPDIR=$(dirname "$0")

source "$TOPDIR/lib/functions.sh"
source "$TOPDIR/lib/bash_arg_parser/arg_parser.sh"

CONF='
    {
     "PREFIX":
       {
        "name":"prefix",
        "short":"x",
        "required": "True",
        "help": "VM name"
       },
     "CPU":
       {
        "name":"cpu",
        "short":"c",
        "default": "4",
        "required": "True",
        "help": "CPU Number for VM"
       },
     "RAM":
       {
        "name":"ram",
        "short":"r",
        "default": "8192",
        "required": "True",
        "help": "RAM in MB for VM"
       },
     "DISK":
       {
        "name":"disk",
        "short":"d",
        "default": "60",
        "required": "True",
        "help": "Disk size in GB for VM"
       },
     "POOL":
       {
        "name":"pool",
        "short":"p",
        "default": "big",
        "reuired": "True",
        "help": "Storage pool name. big: HDD or default: SSD"
       },
     "ISO":
       {
        "name":"iso",
        "short":"i",
        "default": "fuel.iso",
        "reuired": "True",
        "help": "Path to FUEL ISO file"
       },
     "GATEWAY_IP":
       {
        "name":"gateway",
        "short":"g",
        "default": "172.18.161.1",
        "reuired": "False",
        "help": "Default Gateway IP"
       },
     "PXE_VLAN":
       {
        "name":"vlan",
        "short":"v",
        "required": "True",
        "help": "PXE VLAN ID"
       }
    }'


### Argument parsing

WORKDIR="${TOPDIR}/lib/bash_arg_parser"
arg_parser "${CONF}" "$*"


### Setting up variables

NAME="${PREFIX}-${PXE_VLAN}-fuel"

ISO="$TOPDIR/$ISO"

fail_if_not_root

is_iso_exist "${ISO}"


### Confirm parameters

echo
echo "Your parameters are the following:"
echo "           Name: ${NAME}"
echo "            CPU: ${CPU}"
echo "            RAM: ${RAM}"
echo "           DISK: ${DISK}"
echo "       PXE VLAN: ${PXE_VLAN}"


### Start creating

create_volume  "${NAME}" "${DISK}" "${POOL}"

set_image_path "${NAME}" "${POOL}"

deploy_fuel    "${NAME}" "${CPU}" "${RAM}" \
               "${ISO}"  "${GATEWAY_IP}" \
               "${PXE_VLAN}" \
               "${IMAGE_PATH}"

