#!/bin/bash

TOPDIR=$(dirname "$0")

source "$TOPDIR/lib/functions.sh"
source "$TOPDIR/lib/bash_arg_parser/arg_parser.sh"

CONF='
    {
     "PREFIX":
       {
        "name":"prefix",
        "short":"x",
        "required": "True",
        "help": "VM name"
       },
     "CPU":
       {
        "name":"cpu",
        "short":"c",
        "default": "2",
        "required": "True",
        "help": "CPU Number for VM"
       },
     "RAM":
       {
        "name":"ram",
        "short":"r",
        "default": "4096",
        "required": "True",
        "help": "RAM in MB for VM"
       },
     "DISK":
       {
        "name":"disk",
        "short":"d",
        "default": "40",
        "required": "True",
        "help": "Disk size in GB for VM"
       },
     "POOL":
       {
        "name":"pool",
        "short":"p",
        "default": "big",
        "reuired": "True",
        "help": "Storage pool name. big: HDD or default: SSD"
       },
     "MGMT_VLAN":
       {
        "name":"management_vlan",
        "short":"m",
        "reuired": "True",
        "help": "Management VLAN ID"
       },
     "STRG_VLAN":
       {
        "name":"storage_vlan",
        "short":"s",
        "reuired": "True",
        "help": "Storage VLAN ID"
       },
     "PXE_VLAN":
       {
        "name":"vlan",
        "short":"v",
        "required": "True",
        "help": "PXE VLAN ID"
       }
    }'


### Argument parsing

WORKDIR="${TOPDIR}/lib/bash_arg_parser"
arg_parser "${CONF}" "$*"


### Setting up variables

generate_mac

NAME="${PREFIX}-${PXE_VLAN}-mos_$MAC_END"

fail_if_not_root


### Confirm parameters

echo
echo "Your parameters are the following:"
echo "           Name: ${NAME}"
echo "            CPU: ${CPU}"
echo "            RAM: ${RAM}"
echo "           DISK: ${DISK}"
echo "       PXE VLAN: ${PXE_VLAN}"
echo "Management VLAN: ${MGMT_VLAN}"
echo "   Storage VLAN: ${STRG_VLAN}"
echo


### Start creating

create_volume  "${NAME}" "${DISK}" "${POOL}"


set_image_path "${NAME}" "${POOL}"

deploy_slave "${NAME}" "${CPU}" "${RAM}" \
             "${MAC}" \
             "${PXE_VLAN}" "${MGMT_VLAN}" "${STRG_VLAN}" \
             "${IMAGE_PATH}"

